### ISSUE TITLE
focus border on accordion groups

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#54]
5.0.0-beta.9 added a grey focus border on accordion groups.  It looks a little...off.  Was this intentional?

![image](https://user-images.githubusercontent.com/5713608/45714660-e1d23a00-bb57-11e8-9925-e79fd2ad5511.png)

**Comment by smlombardi** [comment]
Bootstrap 4.1 switched accordions into buttons, so that's why.

**Comment by smlombardi** [comment]
Bootstrap 4.1 accordions are buttons. So that may be causing it.  However, if you look a the accordions page on the web site there are no focus rings: https://ng.designsystem.pitneycloud.com/web/accordions

<img width="914" alt="screen shot 2018-09-18 at 4 35 51 pm" src="https://user-images.githubusercontent.com/835148/45714911-efd88880-bb60-11e8-9494-7c115119ce5c.png">

**Comment by smlombardi** [comment]
Beta 10 fixes, they now have underlines in Chrome.

<img width="920" alt="screen shot 2018-10-11 at 11 14 57 am" src="https://user-images.githubusercontent.com/835148/46814548-f8c70f00-cd46-11e8-9197-88cc93b1066e.png">
